[2022-07-01 15:26:16,073] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: ingest_data.get_data_to_ingest_from_local_file_task scheduled__2022-06-30T22:19:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2022-07-01 15:26:16,076] {local_task_job.py:101} INFO - Task is not able to be run
